import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api, setSession, previewImage } from './api.js';
import './style.css';

const label = key => key.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, char => char.toUpperCase()).replace(/Ids$/, 'selections');
const projectTemplate = { id: '', title: '', tagline: '', location: '', category: '', year: '', client: '', area: '', status: '', description: '', heroImage: '', heroAlt: '', galleryImages: [], comparison: null, drawings: [], renders: [], story: [], hidden: false };
const templates = {
  projects: projectTemplate, team: { name: '', role: '', image: '', alt: '' }, galleryImages: { url: '', caption: '', alt: '' },
  drawings: { name: '', url: '', alt: '' }, renders: { name: '', url: '', alt: '' }, story: { heading: '', text: '', image: '', alt: '' },
  socials: { name: '', url: '' }, services: { num: '', title: '', desc: '' }, processSteps: { num: '', title: '', desc: '' }
};
const blank = value => typeof value === 'string' ? '' : Array.isArray(value) ? [] : typeof value === 'boolean' ? false : typeof value === 'number' ? 0 : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value).filter(([key]) => key !== '_key').map(([key, item]) => [key, blank(item)])) : null;
const protectedKeys = ['_key'];

function MediaPicker({ onSelect, onClose }) {
  const [items, setItems] = useState([]), [search, setSearch] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const load = () => api('/media').then(result => setItems(result.items)).catch(error => setMessage(error.message));
  useEffect(() => { load(); }, []);
  async function upload(files) {
    setBusy(true); let succeeded = 0;
    for (const file of files) {
      setMessage(`Uploading ${file.name} (${succeeded + 1}/${files.length})`);
      const form = new FormData(); form.append('file', file);
      try { await api('/media', { method: 'POST', body: form }); succeeded++; }
      catch (error) { setMessage(`${file.name}: ${error.message}. Choose the files again to retry.`); setBusy(false); await load(); return; }
    }
    setMessage(`${succeeded} photograph${succeeded === 1 ? '' : 's'} uploaded`); setBusy(false); await load();
  }
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Media library">
    <header className="modal-header"><div><span className="eyebrow">ASSET LIBRARY</span><h2>Choose a photograph</h2></div><button onClick={onClose}>Close</button></header>
    <div className="media-tools"><input aria-label="Search media" placeholder="Search by filename…" value={search} onChange={e => setSearch(e.target.value)} /><label className="button primary">{busy ? 'Uploading…' : 'Upload photographs'}<input className="file-input" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e => upload([...e.target.files])} /></label></div>
    <p className="help">JPEG, PNG or WebP, up to 15 MB each. Uploads are processed one at a time. Existing photographs are the site's current mockups.</p>
    {message && <p role="status" className="notice">{message}</p>}
    <div className="media-grid">{items.filter(item => item.name.toLowerCase().includes(search.toLowerCase())).map(item => <div className="asset-wrap" key={item.id}><button className="asset" onClick={() => onSelect(item.url)}><img src={previewImage(item.thumbnail)} alt="" loading="lazy" /><span>{item.name}</span></button>{!item.existing && <button className="asset-delete danger-text" disabled={busy} onClick={async () => { if (!confirm('Permanently delete this unused upload? Referenced images cannot be deleted.')) return; try { await api(`/media/${item.id}`, { method: 'DELETE' }); setMessage('Unused photograph deleted.'); await load(); } catch (error) { setMessage(error.message); } }}>Delete unused upload</button>}</div>)}</div>
    {!items.length && <p>No uploaded photographs yet.</p>}
  </section></div>;
}

function Editor({ value, onChange, name, path = '', content, pickMedia }) {
  const key = path.split('.').at(-1) || name;
  if (Array.isArray(value)) {
    const add = () => onChange([...value, structuredClone(templates[key] || (value.length ? blank(value[0]) : ''))]);
    const move = (index, direction) => { const next = [...value]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; onChange(next); };
    if (key === 'featuredIds') return <fieldset><legend>Featured project selection and order</legend><p className="help">Only selected projects appear on Home. Use the arrows to reorder.</p>{value.map((id, i) => <div className="repeat-line" key={i}><select aria-label={`Featured project ${i + 1}`} value={id} onChange={e => onChange(value.map((entry, j) => j === i ? e.target.value : entry))}>{content.projects.map(project => <option key={project._key || project.id} value={project.id}>{project.title || project.id || 'Untitled'}</option>)}</select><button disabled={!i} onClick={() => move(i, -1)}>↑</button><button disabled={i === value.length - 1} onClick={() => move(i, 1)}>↓</button><button onClick={() => onChange(value.filter((_, j) => j !== i))}>Remove</button></div>)}<button onClick={() => onChange([...value, content.projects.find(p => !value.includes(p.id))?.id || ''])} disabled={!content.projects.some(p => !value.includes(p.id))}>Add featured project</button></fieldset>;
    return <fieldset className="collection"><legend>{name || label(key)} <span className="count">{value.length}</span></legend>
      {value.map((item, index) => <details className="repeat-item" key={index} open={typeof item !== 'object' || item === null}><summary>{typeof item === 'object' && item ? item.title || item.name || item.heading || item.caption || `Item ${index + 1}` : `Item ${index + 1}`}</summary>
        <div className="repeat-actions"><button disabled={!index} onClick={() => move(index, -1)}>↑ Move up</button><button disabled={index === value.length - 1} onClick={() => move(index, 1)}>↓ Move down</button><button className="danger-text" onClick={() => { if (confirm('Remove this entry from the draft? The media file will remain available.')) onChange(value.filter((_, i) => i !== index)); }}>Remove</button></div>
        <Editor value={item} onChange={next => onChange(value.map((entry, i) => i === index ? next : entry))} name={`Item ${index + 1}`} path={`${path}.${index}`} content={content} pickMedia={pickMedia} />
      </details>)}<button className="add-button" onClick={add}>+ Add {key === 'galleryImages' ? 'photograph' : 'entry'}</button>
    </fieldset>;
  }
  if (value === null && key === 'comparison') return <div className="optional"><p>No before / after comparison.</p><button onClick={() => onChange({ beforeImage: '', afterImage: '', beforeAlt: '', afterAlt: '', beforeLabel: 'Before', afterLabel: 'After', caption: '' })}>Add comparison</button></div>;
  if (value && typeof value === 'object') return <div className="object-fields">{Object.entries(value).filter(([entry]) => !protectedKeys.includes(entry)).map(([entry, item]) => {
    const change = next => onChange({ ...value, [entry]: next });
    const childPath = path ? `${path}.${entry}` : entry;
    return (item && typeof item === 'object') || entry === 'comparison' ? <details className="field-section" key={entry}><summary>{label(entry)}</summary><div className="section-body">{entry === 'comparison' && item && <button className="danger-text" onClick={() => change(null)}>Remove comparison</button>}<Editor value={item} onChange={change} name={label(entry)} path={childPath} content={content} pickMedia={pickMedia} /></div></details> : <Editor key={entry} value={item ?? ''} onChange={change} name={label(entry)} path={childPath} content={content} pickMedia={pickMedia} />;
  })}</div>;
  if (typeof value === 'boolean') return <label className="checkbox-field"><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} />{name}</label>;
  const image = /image|favicon/i.test(key) || (key === 'url' && /galleryImages|drawings|renders/.test(path));
  const multiline = /description|paragraph|intro|text|body|caption|headline|success|messagePlaceholder/i.test(key) || String(value).length > 130;
  const control = typeof value === 'number' ? <input type="number" min="0" value={value} onChange={e => onChange(Math.max(0, Number(e.target.value)))} /> : multiline && !image ? <textarea rows={3} value={value} onChange={e => onChange(e.target.value)} /> : <input type="text" value={value ?? ''} onChange={e => onChange(e.target.value)} />;
  return <div className={`field ${image ? 'image-field' : ''}`}><label><span>{name || label(key)}</span>{control}</label>{image && <div className="image-controls">{value && <img src={previewImage(value)} alt="Selected photograph" loading="lazy" />}<button onClick={() => pickMedia(url => onChange(url))}>Choose photograph</button>{value && <button onClick={() => onChange('')}>Clear</button>}</div>}{key === 'id' && <small>URL slug: lowercase words separated by hyphens. Existing links redirect after publishing.</small>}</div>;
}

function Login({ onLogin }) {
  const [setup, setSetup] = useState(false), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { api('/auth/status').then(data => setSetup(data.setupAvailable)).catch(err => setError(err.message)); }, []);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const session = await api(setup ? '/auth/setup' : '/auth/login', { method: 'POST', body: { email, password } }); onLogin(session); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <main className="login-shell"><div className="login-art"><span className="eyebrow">BLUEPRINT DESIGN STUDIO</span><h1>A considered space<br />for your content.</h1><p>Pages, projects, and photographs.<br />One place to keep your studio up to date.</p><div className="drafting-mark">B / P</div></div><section className="login-card"><span className="eyebrow">CONTENT STUDIO</span><h2>{setup ? 'Create your owner account' : 'Welcome back'}</h2><p>{setup ? 'This one-time local setup creates the administrator. Existing website content is already imported.' : 'Sign in to manage your website.'}</p><form onSubmit={submit}><label>Email<input type="email" required autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" required minLength={12} maxLength={256} autoComplete={setup ? 'new-password' : 'current-password'} value={password} onChange={e => setPassword(e.target.value)} /></label><small>Use at least 12 characters.</small>{error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Please wait…' : setup ? 'Create owner account' : 'Sign in'}</button></form></section></main>;
}

const navigation = [ ['overview', 'Overview'], ['home', 'Home page'], ['projectsPage', 'Projects page'], ['about', 'About page'], ['contact', 'Contact page'], ['projects', 'Projects'], ['team', 'Team'], ['media', 'Media library'], ['settings', 'Site settings'], ['history', 'Publication history'], ['enquiries', 'Enquiries'], ['account', 'Account'] ];

function App() {
  const [session, setUser] = useState(undefined), [draft, setDraft] = useState(null), [version, setVersion] = useState(0), [section, setSection] = useState('overview'), [selected, setSelected] = useState(0), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [failure, setFailure] = useState(''), [picker, setPicker] = useState(null), [preview, setPreview] = useState(false), [history, setHistory] = useState(null), [enquiries, setEnquiries] = useState([]);
  const login = data => { setSession(data); setUser(data); };
  const loadDraft = async () => { const result = await api('/draft'); setDraft(result.content); setVersion(result.version); setDirty(false); };
  useEffect(() => { api('/auth/me').then(login).catch(() => setUser(null)); }, []);
  useEffect(() => { if (session) loadDraft().catch(err => setFailure(err.message)); }, [session?.email]);
  useEffect(() => { const warn = event => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  useEffect(() => { window.scrollTo(0, 0); }, [section]);
  useEffect(() => {
    if (!session) return;
    if (section === 'history') api('/history').then(setHistory).catch(err => setFailure(err.message));
    if (section === 'enquiries') api('/enquiries').then(data => setEnquiries(data.items)).catch(err => setFailure(err.message));
  }, [section, session?.email]);
  const change = next => { setDraft(next); setDirty(true); setNotice(''); };
  const update = (key, value) => change({ ...draft, [key]: value });
  const updateCopy = (key, value) => update('copy', { ...draft.copy, [key]: value });
  const pickMedia = callback => setPicker(() => callback);
  async function save() { if (!dirty) return version; const result = await api('/draft', { method: 'PUT', body: { version, content: draft } }); setVersion(result.version); setDirty(false); setNotice('Draft saved. The public website is unchanged until publication.'); return result.version; }
  async function act(task) { setBusy(true); setFailure(''); try { await task(); } catch (err) { setFailure(err.message); if (err.status === 401) { setUser(null); setSession(null); } } finally { setBusy(false); } }
  async function publish() {
    if (!confirm('Publish all content in the saved draft? This includes changes across all pages and projects.')) return;
    await act(async () => { const savedVersion = await save(); const result = await api('/publish', { method: 'POST', body: { version: savedVersion } }); setNotice(`Publication ${result.version} is live locally. Refresh the website to see it.`); });
  }
  const editor = (value, onChange, path) => <Editor value={value} onChange={onChange} path={path} content={draft} pickMedia={pickMedia} />;
  const siteBase = location.port === '3001' ? `${location.protocol}//${location.hostname}:3000` : location.origin;
  if (session === undefined) return <div className="loading">Opening Content Studio…</div>;
  if (!session) return <Login onLogin={login} />;
  if (!draft) return <div className="loading">{failure || 'Loading your content…'}<button onClick={() => loadDraft().catch(err => setFailure(err.message))}>Retry</button></div>;
  const title = navigation.find(([id]) => id === section)?.[1];
  const project = draft.projects[selected];
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href={siteBase} target="_blank" rel="noreferrer"><span>B/P</span><div>Blueprint<small>CONTENT STUDIO</small></div></a><div className="workspace-label">YOUR WEBSITE</div><nav>{navigation.map(([id, text]) => <button key={id} className={section === id ? 'active' : ''} onClick={() => { setSection(id); setFailure(''); }}>{text}<span>↗</span></button>)}</nav><div className="sidebar-bottom"><span className="status-dot" /> Local workspace<small>{session.email}</small><button onClick={() => act(async () => { if (dirty && !confirm('Sign out and discard unsaved edits?')) return; await api('/auth/logout', { method: 'POST' }); setUser(null); setSession(null); setDraft(null); })}>Sign out</button></div></aside>
    <main className="workspace"><header className="topbar"><span>STUDIO / {title.toUpperCase()}</span><a href={siteBase} target="_blank" rel="noreferrer">Open website ↗</a></header><div className="workspace-inner"><header className="page-header"><div><span className="eyebrow">CONTENT MANAGEMENT</span><h1>{title}</h1><p>{dirty ? 'You have unsaved changes.' : `Draft version ${version} · Your current website content, ready to edit.`}</p></div><div className="header-actions"><button disabled={busy} onClick={() => act(async () => { await save(); setPreview(true); })}>Preview</button><button disabled={busy || !dirty} onClick={() => act(save)}>Save draft</button><button className="primary" disabled={busy} onClick={publish}>{busy ? 'Working…' : 'Publish changes'}</button></div></header>
      {notice && <div className="notice" role="status">{notice}</div>}{failure && <div className="error" role="alert">{failure}<button onClick={() => { if (!dirty || confirm('Reload the server draft and discard local edits?')) act(loadDraft); }}>Reload draft</button></div>}
      {section === 'overview' && <><section className="overview-hero"><div><span className="eyebrow">YOUR STUDIO, IN YOUR WORDS</span><h2>Keep every detail<br />considered.</h2><p>Start with a page, refine a project, or choose a photograph.<br />Save your draft, preview, then publish when you're ready.</p><button className="primary" onClick={() => setSection('projects')}>Manage projects ↗</button></div><div className="blueprint-lines"><span>{draft.projects.length.toString().padStart(2, '0')}</span><small>PROJECTS IN YOUR COLLECTION</small></div></section><div className="stats"><button onClick={() => setSection('projects')}><small>PROJECTS</small><strong>{draft.projects.length}</strong><span>Manage your portfolio ↗</span></button><button onClick={() => setSection('team')}><small>TEAM MEMBERS</small><strong>{draft.team.length}</strong><span>Edit profiles ↗</span></button><button onClick={() => setSection('home')}><small>FEATURED PROJECTS</small><strong>{draft.copy.home.featuredIds.length}</strong><span>Curate Home ↗</span></button></div><section className="panel"><h3>Existing content is your starting point</h3><p>The site's current copy and photographs are preserved. No extra sample projects or sections have been published. Every page editor changes a draft; publication updates the website.</p><p className="help">Photographs are mockups until you replace them. Add as many gallery entries as you need, within your storage capacity.</p></section></>}
      {['home', 'about', 'contact', 'projectsPage'].includes(section) && <section className="panel">{editor(draft.copy[section === 'projectsPage' ? 'projects' : section], next => updateCopy(section === 'projectsPage' ? 'projects' : section, next), `copy.${section === 'projectsPage' ? 'projects' : section}`)}{section === 'home' || section === 'projectsPage' ? <details className="field-section"><summary>Shared construction comparison</summary><div className="section-body">{editor(draft.constructionComparison, next => update('constructionComparison', next), 'constructionComparison')}</div></details> : null}{section === 'home' && <details className="field-section"><summary>Testimonial</summary><div className="section-body">{editor(draft.studioInfo.quote, next => update('studioInfo', { ...draft.studioInfo, quote: next }), 'studioInfo.quote')}</div></details>}</section>}
      {section === 'settings' && <section className="panel">{editor({ studioInfo: draft.studioInfo, branding: draft.copy.branding, nav: draft.copy.nav, footer: draft.copy.footer, seo: draft.copy.seo, detail: draft.copy.detail, accessibility: draft.copy.accessibility, interface: draft.copy.interface, categories: draft.categories, services: draft.services, processSteps: draft.processSteps }, next => change({ ...draft, studioInfo: next.studioInfo, categories: next.categories, services: next.services, processSteps: next.processSteps, copy: { ...draft.copy, ...Object.fromEntries(['branding', 'nav', 'footer', 'seo', 'detail', 'accessibility', 'interface'].map(key => [key, next[key]])) } }), 'settings')}<p className="help">Services, process steps, socials and some studio story fields are preserved from the source but currently have no visible site section. Editing them does not add a new section.</p></section>}
      {section === 'team' && <section className="panel"><p className="help">About currently shows the first {draft.copy.about.visibleTeamCount} members. Change the visible team count in the About editor to show more or fewer.</p>{editor(draft.team, next => update('team', next), 'team')}</section>}
      {section === 'projects' && <div className="project-workspace"><section className="project-list"><div className="list-heading"><h3>Collection</h3><button onClick={() => { const next = { ...structuredClone(projectTemplate), _key: crypto.randomUUID(), id: `project-${Date.now()}`, category: draft.categories[0] || '' }; update('projects', [...draft.projects, next]); setSelected(draft.projects.length); }}>+ Add project</button></div>{draft.projects.map((item, index) => <button className={selected === index ? 'selected' : ''} key={item._key || index} onClick={() => setSelected(index)}>{item.heroImage ? <img src={previewImage(item.heroImage)} alt="" /> : <span className="project-placeholder">B/P</span>}<span>{item.title || 'Untitled project'}<small>{item.hidden ? 'Hidden from website' : item.category || 'Draft'}</small></span></button>)}</section><section className="panel project-editor">{project ? <><div className="project-actions"><button disabled={!selected} onClick={() => { const next = [...draft.projects]; [next[selected - 1], next[selected]] = [next[selected], next[selected - 1]]; update('projects', next); setSelected(selected - 1); }}>↑</button><button disabled={selected === draft.projects.length - 1} onClick={() => { const next = [...draft.projects]; [next[selected + 1], next[selected]] = [next[selected], next[selected + 1]]; update('projects', next); setSelected(selected + 1); }}>↓</button><button onClick={() => { const duplicate = structuredClone(project); duplicate.id += `-copy-${Date.now()}`; duplicate._key = crypto.randomUUID(); duplicate.hidden = true; update('projects', [...draft.projects, duplicate]); setSelected(draft.projects.length); }}>Duplicate</button><button className="danger-text" onClick={() => { if (confirm('Remove this project from the draft? It can be recovered from publication history.')) { change({ ...draft, projects: draft.projects.filter((_, i) => i !== selected), copy: { ...draft.copy, home: { ...draft.copy.home, featuredIds: draft.copy.home.featuredIds.filter(id => id !== project.id) } } }); setSelected(Math.max(0, selected - 1)); } }}>Remove project</button></div>{editor(project, next => {
          let content = { ...draft, projects: draft.projects.map((entry, i) => i === selected ? next : entry) };
          if (next.id !== project.id) content.copy = { ...draft.copy, home: { ...draft.copy.home, featuredIds: draft.copy.home.featuredIds.map(id => id === project.id ? next.id : id) } };
          change(content);
        }, `projects.${selected}`)}<button onClick={() => update('projects', draft.projects.map((entry, i) => i === selected ? { ...entry, sectionCopy: structuredClone(draft.copy.detail) } : entry))}>Customize this project's section headings</button></> : <p>No projects. Add one to begin.</p>}</section></div>}
      {section === 'media' && <section className="panel"><h2>Photographs, ready to reuse</h2><p>Upload your own photographs or browse the site's existing mockups. Selecting an image here copies its URL for use in an editor.</p><button className="primary" onClick={() => pickMedia(url => { navigator.clipboard.writeText(url).then(() => setNotice('Image URL copied. Choose photographs directly inside any content field.')).catch(() => setNotice(`Image URL: ${url}`)); })}>Open media library</button></section>}
      {section === 'history' && <section className="panel"><h2>Published versions</h2><p>Restore a version into the draft, preview it, then publish. Your live website is unchanged until you publish.</p>{history?.items.map(item => <div className="history-row" key={item.id}><div><strong>Version {item.id}{history.active === item.id ? ' · Active' : ''}</strong><small>{new Date(item.created_at).toLocaleString()}</small></div><button disabled={busy} onClick={() => { if (confirm('Replace the current draft with this publication?')) act(async () => { await api(`/restore/${item.id}`, { method: 'POST', body: { version } }); await loadDraft(); setNotice('Version restored into the draft. Preview before publishing.'); }); }}>Restore to draft</button></div>)}</section>}
      {section === 'enquiries' && <section className="panel"><h2>Project enquiries</h2><p className="help">Messages are saved here. Email delivery requires configuration before launch.</p>{!enquiries.length && <p>No enquiries yet.</p>}{enquiries.map(item => <article className="enquiry" key={item.id}><header><strong>{item.name}</strong><select aria-label="Enquiry status" value={item.status} onChange={e => act(async () => { await api(`/enquiries/${item.id}`, { method: 'PATCH', body: { status: e.target.value } }); const result = await api('/enquiries'); setEnquiries(result.items); })}><option value="new">New</option><option value="read">Read</option><option value="closed">Closed</option></select></header><a href={`mailto:${item.email}`}>{item.email}</a><small>{item.discipline} · {new Date(item.created_at).toLocaleString()}</small><p>{item.message}</p></article>)}</section>}
      {section === 'account' && <section className="panel narrow"><h2>Change password</h2><form onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); act(async () => { const result = await api('/auth/password', { method: 'POST', body: { currentPassword: values.get('currentPassword'), password: values.get('password') } }); login(result); form.reset(); setNotice('Password changed. Other sessions have been signed out.'); }); }}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={256} /></label><button className="primary" disabled={busy}>Update password</button></form></section>}
    </div></main>
    {picker && <MediaPicker onClose={() => setPicker(null)} onSelect={url => { picker(url); setPicker(null); }} />}
    {preview && <div className="modal-backdrop"><section className="preview-modal" role="dialog" aria-modal="true" aria-label="Website draft preview"><header><strong>Saved draft preview · Changes are not public</strong><a href={`${siteBase}/?preview=1`} target="_blank" rel="noreferrer">Open in new tab ↗</a><button onClick={() => setPreview(false)}>Close</button></header><iframe title="Draft website" src={`${siteBase}/?preview=1`} /></section></div>}
  </div>;
}

createRoot(document.getElementById('root')).render(<App />);
