import * as original from '../../src/data/seed.js';

// These literals are transcribed from the current views. No new public copy or projects.
export function createSeed() {
  return {
    ...structuredClone({ ...original }),
    projects: original.projects.map(project => ({ ...structuredClone(project), _key: project.id, heroAlt: project.title, hidden: false })),
    copy: {
      branding: { logoFirst: 'Blueprint', logoSecond: 'Design Studio', logoImage: '', logoAlt: 'Blueprint Design Studio', favicon: '', titleSuffix: 'BLUE PRINT' },
      nav: { home: 'Home', about: 'About', projects: 'Projects', contact: 'Contact', cta: 'Build with Us', ctaUrl: '/contact', menuLabel: 'Toggle Menu' },
      footer: { name: 'Blueprint Design Studio', location: 'Civil Lines, Prayagraj' },
      home: { title: 'Architecture Studio', headlineFirst: 'Spaces drawn with intention,', headlineEmphasis: 'built', headlineLast: ' with precision', workButton: 'View Our Work', workUrl: '/projects', contactButton: 'Build with Us', contactUrl: '/contact', workHeading: 'Selected Work', allProjects: 'View All Projects', showComparison: true, showQuote: true, featuredIds: original.projects.slice(0, 3).map(p => p.id) },
      projects: { title: 'Selected Projects', eyebrow: 'PORTFOLIO ARCHIVE', heading: 'Selected Works', intro: 'Spaces drawn with intention, built with precision across residential, commercial, and interior sectors.', all: 'All', empty: 'No projects found in this category.', showComparison: true },
      about: { title: 'Our Story & Approach', heading: 'About the Studio', teamEyebrow: 'Our Team', teamHeading: 'Meet Our Team', teamIntro: 'Our multidisciplinary studio brings together architectural clarity, structural precision, and tailored interior craftsmanship.', headline: 'Quiet, functional, and deeply intentional spaces.', paragraphs: [original.studioInfo.aboutStory.shortIntro, 'From initial drafting through structural coordination and interior turnkey joinery, our work emphasizes geometric restraint, natural illumination, and honest materials.'], visibleTeamCount: 4, showTeam: true, ctaHeading: 'Ready to discuss your site or renovation?', ctaBody: 'Connect with our Civil Lines office in Prayagraj.', ctaPrimary: 'Get in Touch', ctaPrimaryUrl: '/contact', ctaSecondary: 'Build with Us', ctaSecondaryUrl: '/contact' },
      contact: { title: 'Start a Project', eyebrow: 'INQUIRIES', heading: 'Start a Conversation', intro: 'Whether planning a new build, interior fit-out, or adaptive renovation, we welcome your project brief.', locationLabel: 'STUDIO LOCATION', studioName: 'Blueprint Design Studio', enquiryLabel: 'DIRECT INQUIRIES', emailLabel: 'Email:', phoneLabel: 'Phone:', hoursLabel: 'HOURS', appointment: 'By prior appointment', formHeading: 'Project Outline', nameLabel: 'Full Name *', namePlaceholder: 'Your name', emailFieldLabel: 'Email Address *', emailPlaceholder: 'your@email.com', disciplineLabel: 'Discipline *', disciplinePlaceholder: 'Select a category', disciplines: ['Interiors', 'Architecture', 'Commercial', 'Design to Build'], messageLabel: 'Project Brief & Location *', messagePlaceholder: 'Brief outline of scope, site location, and timeline...', submit: 'Send Inquiry', successHeading: 'Message Received', success: 'Thank you, {name}. Our studio directors will review your project brief and get in touch within 24–48 hours.', successLink: 'View Portfolio' },
      detail: { title: 'Project Detail', missingHeading: 'Project Not Found', missingText: 'The requested project does not exist.', missingLink: 'Back to Portfolio', client: 'Client', location: 'Location', year: 'Year', area: 'Area', category: 'Project Type', status: 'Status', brief: 'The Project Brief', storyLabel: '{projectTitle} Story', galleryEyebrow: 'Gallery', galleryHeading: 'Project Gallery', galleryIntro: 'A collection of exterior, interior, and macro details capturing the spatial texture.', drawingsEyebrow: 'Drafts', drawingsHeading: 'The Architectural Design', drawingsIntro: 'Architectural plans, sections, and site drawings defining the structural geometry.', rendersEyebrow: 'Visualization', rendersHeading: 'Visualizing the Space', rendersIntro: 'Volumetric massing renders and 3D modeling drafts prepared during the development phase.', comparisonEyebrow: 'Transformation', comparisonHeading: 'Construction vs Completion', comparisonIntro: 'Slide to compare the active building phase with the realized architectural volume.', before: 'BEFORE', after: 'AFTER' },
      accessibility: { lightboxClose: 'Close Lightbox', lightboxPrevious: 'Previous Image', lightboxNext: 'Next Image', comparison: 'Before and after comparison slider' },
      seo: { title: 'Blueprint Design Studio | Architecture & Interiors, Prayagraj', description: original.studioInfo.tagline, image: '' },
      interface: { loadMore: 'Load more photographs', retry: 'Retry', unavailable: 'The content service is unavailable. Please retry.', enquiryError: 'Your enquiry could not be saved. Please try again.' }
    },
    categories: ['Interiors', 'Architecture', 'Commercial'],
    // Preserve the currently visible archive choices and exact project categories on import.
  };
}
